### ISSUE TITLE
Reset sent messages

### ISSUE THREAD

**Issue by gulipad** [davidmann4/botstack#31]
I am constantly running into this same issue while developing. I get an error and the app crashes. I fix the error, and when testing again it crashes because it registers the previously sent message as the current one. Any way to reset the messages sent to the bot through FB messenger?

**Comment by davidmann4** [comment]
Hi, interssting - guess you return 500 to facebook 

if you uncomment stuff at 

https://github.com/davidmann4/botstack/blob/master/lib/bot/base_bot_logic.rb#L211

you should be fine 

cheers

**Comment by davidmann4** [comment]
solved it?

**Comment by davidmann4** [comment]
newest version has it fixed
